version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    volumes:
      - ${MYSQL_HOST_DIR}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
